bookkeeper_manager:
    resource: "@BookkeeperManagerBundle/Resources/config/routing.yml"
    prefix:   /book

bookkeeper_hell_world:
    resource: "@BookkeeperHellWorldBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
